### ISSUE TITLE
LinkError: WebAssembly Instantiation: Import #3

### ISSUE THREAD

**Issue by bainternet** [procoru/xmr-stak-cpu-emscripten#1]
Hi so what state is this project in,
I tested it and I get 
failed to asynchronously prepare wasm: LinkError: WebAssembly Instantiation: Import #3 module="env" function="__ZN5httpd5oInstE" error: global import must be a number.

Uncaught (in promise) LinkError: WebAssembly Instantiation: Import #3 module="env" function="__ZN5httpd5oInstE" error: global import must be a number.

**Comment by kschieck** [comment]
Check for linking errors (or warnings) when compiling emscripten build.

I had the same error and it was that I had defined

`static const int FOO = 1;`

where I should have had

```
static const int FOO;
... 
// in .cc file
const int ClassName::FOO = 1
```
